apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-july17-rhoai
  janus-idp.io/tekton: test-july17-rhoai
  backstage.io/kubernetes-id: test-july17-rhoai
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-july17-rhoai
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- rhoai/